/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import java.io.IOException;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import static printerCsv.ReadPrinters.PrinterRead;



/**
 *
 * @author Ausyarr
 */
public class MainGui extends javax.swing.JFrame {

    public MainGui() {
        initComponents();
       // displaySystemInfo();
        
    }
    
    public static String RunCommand(String command) throws IOException {
        /* Runs system commands such as Ipconfig & SystemInfo and returns
        the output as a string. Throws Exceptions if command is invalid.
        */
        Runtime rt = Runtime.getRuntime();
        Process pr = rt.exec(command);
        BufferedReader in = new BufferedReader(new InputStreamReader(pr.getInputStream(), "UTF-8"));
        StringBuilder sBuild = new StringBuilder(); 
        String line;
        while((line = in.readLine()) != null){
            sBuild.append(line);
        }
        in.close();
        return sBuild.toString();
    }
    
    public String[] systemInfo(String args[]) {
        /*
        
        */
        String testOutput = null;
        try {
            testOutput = RunCommand("systeminfo /FO CSV /NH");
            TestTextArea.setText(testOutput);
        } catch (IOException ex) {
            Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] systemInfoArray = testOutput.split("\",\"");
        return systemInfoArray;
    }
    
    public void displaySystemInfo(){
        String[] systemInfoArray = systemInfo(null);
        
        hostNameField.setText(systemInfoArray[0].replace("\"", ""));
        osVersionField.setText(systemInfoArray[1].replace("Microsoft", "").trim());
        osDetailField.setText(systemInfoArray[2]);
        loggedUserField.setText(systemInfoArray[6]);
        
        String[] installDateArray = systemInfoArray[9].split(",");
        installDateField.setText(installDateArray[0]);
        installTimeField.setText(installDateArray[1].trim());
        
        machineModelField.setText(systemInfoArray[12]);
        machineBuilderField.setText(systemInfoArray[11]);
        machineBaseField.setText(systemInfoArray[13]);
        
        ramMaxField.setText(systemInfoArray[22]);
        ramUseField.setText(systemInfoArray[23]);
        
        ramVirtualMaxField.setText(systemInfoArray[24]);
        ramVirtualUseField.setText(systemInfoArray[26]);
        pagefileField.setText(systemInfoArray[27]);
        
        domainField.setText(systemInfoArray[28]);
        logonServerField.setText(systemInfoArray[29]);
        
        hotfixField.setText(systemInfoArray[30].substring(0, 3));
        nicField.setText(systemInfoArray[31].substring(0, 2));
        
        nicTestingField.setText(systemInfoArray[31]);
        
        //  //
        String nicsArray[] = systemInfoArray[31].split(",\\[");
        int arrLength = nicsArray.length - 1;
        String arrString = Integer.toString(arrLength);
        nicsParsedLabel.setText(arrString +" Parsed");
        for (int i=1; i<arrLength; i++) {
            int strFind = nicsArray[i].indexOf("DHCP Server:");
            if (strFind != -1){
                String strCut = nicsArray[i].substring(strFind);
                String dchpServer = strCut.substring(16 ,strCut.indexOf(",")).trim();
                // Clean Up Code Here //
                
                try {
                    Runtime rt = Runtime.getRuntime();
                    Process pr = rt.exec("net use G: \\\\"+dchpServer+"\\Data /user:oc-dbowd999 Nvidia7805");
                    // net use G: \\10.73.76.1\Data //
                    System.out.print("net use G: \\\\"+dchpServer+"\\Data /user:oc-dbowd999 Nvidia7805");
                } catch (IOException ex) {
                    Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
        //  //
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TestTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        hostNameField = new javax.swing.JTextField();
        osVersionField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        osDetailField = new javax.swing.JTextField();
        loggedUserField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        installDateField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        installTimeField = new javax.swing.JTextField();
        machineModelField = new javax.swing.JTextField();
        machineBuilderField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        machineBaseField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ramMaxField = new javax.swing.JTextField();
        ramUseField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ramVirtualMaxField = new javax.swing.JTextField();
        ramVirtualUseField = new javax.swing.JTextField();
        pagefileField = new javax.swing.JTextField();
        domainField = new javax.swing.JTextField();
        logonServerField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hotfixField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nicField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nicTestingField = new javax.swing.JTextArea();
        nicsParsedLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Get System Info");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        TestTextArea.setColumns(20);
        TestTextArea.setRows(5);
        jScrollPane1.setViewportView(TestTextArea);

        jLabel1.setText("Host Name");

        osVersionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osVersionFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("OS Version");

        osDetailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osDetailFieldActionPerformed(evt);
            }
        });

        loggedUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggedUserFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Current User");

        installDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installDateFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Install Date");

        installTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installTimeFieldActionPerformed(evt);
            }
        });

        machineModelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machineModelFieldActionPerformed(evt);
            }
        });

        machineBuilderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machineBuilderFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Machine Brand");

        machineBaseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machineBaseFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Machine Base");

        jLabel7.setText("Max");

        jLabel8.setText("In Use");

        ramMaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramMaxFieldActionPerformed(evt);
            }
        });

        ramUseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramUseFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Physical Memory");

        jLabel10.setText("Virtuall Memory");

        ramVirtualMaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramVirtualMaxFieldActionPerformed(evt);
            }
        });

        ramVirtualUseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramVirtualUseFieldActionPerformed(evt);
            }
        });

        pagefileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagefileFieldActionPerformed(evt);
            }
        });

        domainField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domainFieldActionPerformed(evt);
            }
        });

        logonServerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logonServerFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Domain");

        jLabel12.setText("Logon Server");

        hotfixField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotfixFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Hotfix(s) Max 999");

        nicField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("NIC(s) Max 99");

        nicTestingField.setColumns(20);
        nicTestingField.setLineWrap(true);
        nicTestingField.setRows(5);
        jScrollPane2.setViewportView(nicTestingField);

        nicsParsedLabel.setText("0 NIC(s) Parsed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hostNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(domainField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logonServerField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hotfixField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nicField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nicsParsedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ramMaxField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ramUseField)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(installDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(installTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(machineBaseField, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(machineModelField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(machineBuilderField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(ramVirtualMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ramVirtualUseField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(osVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(loggedUserField, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                                    .addComponent(osDetailField))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pagefileField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(hostNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(osVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(osDetailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(loggedUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(installTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(installDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(machineBuilderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(machineModelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(machineBaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel9)
                            .addComponent(ramMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ramUseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(pagefileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ramVirtualUseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ramVirtualMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel11)
                            .addComponent(domainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel12)
                            .addComponent(logonServerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel13)
                            .addComponent(hotfixField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel14)
                            .addComponent(nicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nicsParsedLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("systeminfo process", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 961, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nicFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicFieldActionPerformed

    private void hotfixFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotfixFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotfixFieldActionPerformed

    private void logonServerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logonServerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logonServerFieldActionPerformed

    private void domainFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domainFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domainFieldActionPerformed

    private void pagefileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagefileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagefileFieldActionPerformed

    private void ramVirtualUseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramVirtualUseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramVirtualUseFieldActionPerformed

    private void ramVirtualMaxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramVirtualMaxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramVirtualMaxFieldActionPerformed

    private void ramUseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramUseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramUseFieldActionPerformed

    private void ramMaxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramMaxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ramMaxFieldActionPerformed

    private void machineBaseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machineBaseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_machineBaseFieldActionPerformed

    private void machineBuilderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machineBuilderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_machineBuilderFieldActionPerformed

    private void machineModelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machineModelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_machineModelFieldActionPerformed

    private void installTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_installTimeFieldActionPerformed

    private void installDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_installDateFieldActionPerformed

    private void loggedUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggedUserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loggedUserFieldActionPerformed

    private void osDetailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osDetailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osDetailFieldActionPerformed

    private void osVersionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osVersionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_osVersionFieldActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased

    }//GEN-LAST:event_jButton1MouseReleased
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TestTextArea;
    private javax.swing.JTextField domainField;
    private javax.swing.JTextField hostNameField;
    private javax.swing.JTextField hotfixField;
    private javax.swing.JTextField installDateField;
    private javax.swing.JTextField installTimeField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField loggedUserField;
    private javax.swing.JTextField logonServerField;
    private javax.swing.JTextField machineBaseField;
    private javax.swing.JTextField machineBuilderField;
    private javax.swing.JTextField machineModelField;
    private javax.swing.JTextField nicField;
    private javax.swing.JTextArea nicTestingField;
    private javax.swing.JLabel nicsParsedLabel;
    private javax.swing.JTextField osDetailField;
    private javax.swing.JTextField osVersionField;
    private javax.swing.JTextField pagefileField;
    private javax.swing.JTextField ramMaxField;
    private javax.swing.JTextField ramUseField;
    private javax.swing.JTextField ramVirtualMaxField;
    private javax.swing.JTextField ramVirtualUseField;
    // End of variables declaration//GEN-END:variables
}
